- FrontEnd/src/components/HeaderFooter/footer/top/FooterNavigation.jsx
- FrontEnd/src/components/HeaderFooter/header/navbar/Menu.jsx
- FrontEnd/src/components/landing-page/about-section/About.js
User story:
As a user,
I want to review the information about platform
So that I understand what this platform offers and if I am interested in it.
Given I am on the platform
When I click on 'Про нас' button
Then I am redirected to 'Про нас' section on the main page
> #136 about us navigation

- profiles/permissions.py
- profiles/serializers.py
- profiles/tests/test_crud_profile.py
- profiles/views.py
Issue #175 
An authorized user is able to view the page of any Company with hidden contact data of the company.
Once the user presses the buttons "Show phone" or "Show email", the contact data should be shown and the data of the user who provided this action should be logged into the log journal.
Two Profile serializers added: 
- `ProfileSensitiveDataROSerializer`: ReadOnly serializer, returns phone number and email
- `ProfileDetailSerializer`: ReadOnly serializer, returns detail data on profile without email and phone number
`ProfileDetailAPIView` altered:
- `get_serializer_class` method overriden
- all serializer calls in the methods adjusted
- `retrieve` method altered
upd: 
- `get_queryset` removed
- `get_serializer_class` returns proper serializer for the owner on GET request now
- …
> #175 view company sensitive data

- profiles/tests/test_filter_profiles.py
Related issue: #187 
The problem: 
- filter tests fail due to hardcoded values.
Changes: 
- `setUpTestData` removed
- `setUp` changed so now we have 4 profiles, not 12
- changed hardcoded values to normal ones
Result:
- all tests pass no matter in which scope they run 
Comment:
I am really sorry. I hope now everything is fine.
> #187 fix filter tests

- profiles/tests/test_crud_profile.py
- profiles/views.py
Functionality of checking password when delete profile added (destroy method overridden). Tests (delete profile) updated due to changes.
> #260 add check password when delete profile

- FrontEnd/src/components/HeaderFooter/header/navbar/Menu.jsx
- FrontEnd/src/components/SignUp/components/signup/signup-form/SignUpFormContent.js
part of the #124 task [Sign Up: 400 email exists]
2 first commits are duplicated from #255 PR since they are fixing eslint errors after merge conflicts in #248 
after #255 is merged, only 1 file will have changes: `SignUpFormContent`, so please have look only at it
[upd: 09/10 now is up to date state]
> Sign up error handling

- authentication/serializers.py
- profiles/serializers.py
- profiles/tests/test_crud_profile.py
- profiles/views.py
Check password on profile delete was improved. Password validation moved to serializer.
> #Improve check password on profile delete

- FrontEnd/src/components/RestorePassword/UI/dotDecor/DotDecor.js
- FrontEnd/src/components/RestorePassword/UI/dotDecor/DotDecor.module.css
- FrontEnd/src/components/RestorePassword/components/restorepassword/RestorePasswordForm.js
- FrontEnd/src/components/RestorePassword/components/restorepassword/RestorePasswordForm.module.css
- FrontEnd/src/components/RestorePassword/components/restorepassword/SendEmailForm.js
- FrontEnd/src/components/RestorePassword/components/restorepassword/SendEmailForm.module.css
- FrontEnd/src/components/RestorePassword/components/restorepassword/restorepassword-form/EmailFormContent.js
- FrontEnd/src/components/RestorePassword/components/restorepassword/restorepassword-form/EmailFormContent.module.css
- FrontEnd/src/components/RestorePassword/components/restorepassword/restorepassword-form/RestorePasswordFormContent.js
- FrontEnd/src/components/RestorePassword/components/restorepassword/restorepassword-form/RestorePasswordFormContent.module.css
- FrontEnd/src/components/RestorePassword/pages/RestorePasswordFailedPage.js
- FrontEnd/src/components/RestorePassword/pages/RestorePasswordFailedPage.module.css
- FrontEnd/src/components/RestorePassword/pages/RestorePasswordModalPage.js
- FrontEnd/src/components/RestorePassword/pages/RestorePasswordModalPage.module.css
- FrontEnd/src/components/RestorePassword/pages/RestorePasswordPage.js
- FrontEnd/src/components/RestorePassword/pages/RestorePasswordPage.module.css
- FrontEnd/src/components/RestorePassword/pages/RestorePasswordSuccessPage.js
- FrontEnd/src/components/RestorePassword/pages/RestorePasswordSuccessPage.module.css
- FrontEnd/src/components/RestorePassword/pages/SendEmailRestorePassword.module.css
- FrontEnd/src/components/RestorePassword/pages/SendEmailRestorePasswordPage.js
- FrontEnd/src/components/SignUp/components/signup/signup-form/ResendActivationFormContent.js
- FrontEnd/src/components/authorization/LoginPage.jsx
- FrontEnd/src/components/basicPage/BasicPage.jsx
- FrontEnd/src/constants/constants.js
- forum/settings.py
**Info about reset password**
**Page about sending email**
**Form for resetting password**
**Password successfully restored**
**Password restored failed**
> #284 fe restore password

- FrontEnd/src/components/ProfileDetail/DetailedInfo/ReadMore.jsx
- FrontEnd/src/components/ProfileDetail/DetailedInfo/ReadMore.module.css
- FrontEnd/src/components/ProfileDetail/ProfileDetailPage.jsx
Read More component has been updated with Ant Design ellipsis according to design and clarified requirements.
> #300 load more information on profile page

- FrontEnd/src/components/ProfileDetail/DetailedInfo/Company.jsx
- FrontEnd/src/components/ProfileDetail/DetailedInfo/Cooperation.jsx
- FrontEnd/src/components/ProfileDetail/DetailedInfo/Cooperation.module.css
- FrontEnd/src/components/ProfileDetail/DetailedInfo/Logistics.jsx
- FrontEnd/src/components/ProfileDetail/DetailedInfo/Logistics.module.css
- FrontEnd/src/components/ProfileDetail/DetailedInfo/ProductsServices.jsx
- FrontEnd/src/components/ProfileDetail/DetailedInfo/Startup.jsx
- FrontEnd/src/components/ProfileDetail/MainInfo/MainInfoSection.jsx
- FrontEnd/src/components/ProfileDetail/MainInfo/ProfileDetailNavBar.jsx
- FrontEnd/src/components/ProfileDetail/MainInfo/ProfileDetailNavBar.module.css
- FrontEnd/src/components/ProfileDetail/ProfileDetailPage.jsx
- FrontEnd/src/components/profileList/ProfileCard.jsx
- FrontEnd/src/components/profileList/ProfileCard.module.css
- FrontEnd/src/context/ActiveLinksContext.js
- FrontEnd/src/context/DataContext.js
The logic of   active tab highlighting has been updated:
- "Про компанію" is initially highlighted for registered company;
- "Стартап" is initially highlighted for startup;
- another tab is highlighted when user switches to it;
- after page reload, highlighting returns to its initial state;
- only tabs for fields with provided information are shown.
Star button removed for profile owner in profile list.
UPD. Menu tabs functionality has been implemented with Context.
> #305 Active tab highlighting

- FrontEnd/src/components/SignUp/components/signup/signup-form/SignUpFormContent.js
- authentication/serializers.py
- authentication/tests/test_user_registration.py
**CHANGES**
Frontend:
- patterns for email & password are replaced with constants from `constants` file;
- restriction for checkbox group is removed. now either one, or both options can be selected;
- validation of the form changed accordingly. now it is valid with either one checkbox checked, or both.
Backend:
- validation on strictly one option selected removed;
- corresponding test case is adjusted.
> #334 [Authorization] ability to select both company startup

- FrontEnd/src/components/HeaderFooter/footer/short/ShortFooter.jsx
- FrontEnd/src/components/PrivacyPolicyPage/UI/footer/Footer.js
- FrontEnd/src/components/PrivacyPolicyPage/UI/header/Menu.js
- FrontEnd/src/components/PrivacyPolicyPage/UI/header/Profile.js
- FrontEnd/src/components/ProfileDetail/DetailedInfo/DataContacts.jsx
- FrontEnd/src/components/RestorePassword/components/restorepassword/restorepassword-form/EmailFormContent.js
- FrontEnd/src/components/RestorePassword/components/restorepassword/restorepassword-form/EmailFormContent.module.css
- FrontEnd/src/components/RestorePassword/components/restorepassword/restorepassword-form/RestorePasswordFormContent.js
- FrontEnd/src/components/RestorePassword/pages/RestorePasswordPage.js
- FrontEnd/src/components/RestorePassword/pages/SendEmailRestorePasswordPage.js
- FrontEnd/src/components/SignUp/pages/ResendActivationPage.js
- FrontEnd/src/components/SignUp/pages/SignUpModalPage.js
- FrontEnd/src/components/SignUp/pages/SignUpPage.js
- FrontEnd/src/components/authorization/LoginPage.jsx
- FrontEnd/src/components/authorization/SignUpInvitation.jsx
- FrontEnd/src/components/errorPages/ErrorPage404.jsx
- FrontEnd/src/context/AuthContextProvider.js
- FE bugs related to reset password functionality were fixed according to the bug reports.
Extra fixes:
- 'a' tag was replaced with Link element in project components.
- useEffect for login/logout depending on token existence was removed in AuthContextProvider (it caused an unexpected behavior for unauthorized user - redirection to main page after reloading)
> #436 [Reset Password] Fix UI defects

- configs/nginx/nginx.conf
- images/tests/test_banner.py
- images/tests/test_logo.py
- validation/validate_image.py
Increase nginx max size for files to 10M. It will show Error messages for files bigger than 5Mb (banner) and 1 Mb (logo). It will show 413 Error when file is bigger than 10 Mb. I can increase 10 Mb if we need it.
BE tests pass ok locally, but fail on GitHub. So it'll be my next task
> #image size bug on deploy

- .github/workflows/tests_be.yml
- forum/settings.py
- forum/urls.py
- requirements.txt
Django Debug Toolbar has been added to the project.
But I have an issue.
It runs well locally, without containers. 
But when I build all the containers provided by the project, I have to add to the project urls.py:
"from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()"
so that Debug Toolbar and Browsable API work correctly (otherwise static files of drf and debug toolbar are not accessible).
I'm not sure if this is my local problem or if I have to add that to the project code.
> #493 Django Debug Toolbar added to the project

- FrontEnd/src/components/SearchPage/Search.jsx
- FrontEnd/src/components/landing-page/companies/Companies.jsx
- FrontEnd/src/components/profileList/ProfileListPage.jsx
- FrontEnd/src/tests/MainCompanies.test.js
The profiles ordering has been corrected according to the requirements:
- list of companies/startups - in alphabetical order;
- list of saved companies - in chronological order (newest first);
- search results -  in alphabetical order.
> #505 [FE] Fix profiles order in lists

- FrontEnd/src/components/HeaderFooter/header/menu/HeaderMenu.jsx
- FrontEnd/src/components/profileList/ProfileListPage.jsx
- profiles/fixtures/activities.yaml
According to bug #462, the operation of the "other services" tab has been corrected.
Also added the generation of the "other services" category to the fixtures.
> #462 create a other services tab

- profiles/serializers.py
- profiles/tests/test_crud_profile.py
There was no possibility to save multiple objects with blank values for optional unique fields. This was fixed by overriding to_internal_value method. An optional unique field is set to None if it is an empty string.
> #568 Fix bug with optional unique char fields

- FrontEnd/src/components/HeaderFooter/header/navbar/SearchBox.jsx
- FrontEnd/src/components/SearchPage/Search.jsx
- FrontEnd/src/components/profileList/ProfileListPage.jsx
Pages have been added to the query parameters for profile lists and search results. 
Now, users can navigate using browser navigation, and the corresponding page is displayed. Previously, users were always redirected to the first page when pressing the go back arrow, regardless of their previous page.
> #593 [FE] Add pages to query params for profile lists

- FrontEnd/src/components/CookiesPolicyPage/LinkContainer.jsx
- FrontEnd/src/components/CookiesPolicyPage/cookiesPolicyComponent.module.css
- FrontEnd/src/components/HeaderFooter/footer/top/FooterPolicy.jsx
- FrontEnd/src/components/HeaderFooter/footer/top/FooterPolicy.module.css
- FrontEnd/src/components/terms-and-conditions-app/terms_conditions/text.js
The task was to update the information on the existing "Terms and conditions of use of the site" page to ensure it reflects the latest privacy practices and regulations
I changed terms and conditions page according to document, also changed footer and container element link to ukrainian.
> #634 update rules and conditions of use of the site

- .github/workflows/black.yml
- .github/workflows/db_deploy.yaml
- .github/workflows/django_cd_dev.yml
- .github/workflows/django_cd_prod.yml
- .github/workflows/django_ci.yml
- .github/workflows/eslint.yml
- .github/workflows/nginx_deploy.yaml
- .github/workflows/pgadmin_deploy.yaml
- .github/workflows/tests_be.yml
- .github/workflows/tests_fe.yml
The problem occurred during the last workflow:
The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/checkout@v3.
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
Necessary updates have been made.
> #669 Update Workflows

- FrontEnd/src/components/ProfilePage/FormComponents/ChangePassword.jsx
new_password field error handling has been updated.
Appropriate messages are returned on UI for password validation errors on the backend:
- "Пароль занадто поширений. Створіть інший пароль." for "This password is too common". 
- "Пароль подібний на іншу персональну інформацію облікового запису. Створіть інший пароль." for "The password is too similar to the ..."
> #677 Update new password field error handling

- BackEnd/authentication/serializers.py
- BackEnd/profiles/serializers.py
- BackEnd/profiles/templates/profiles/email_template.html
- BackEnd/profiles/views.py
- BackEnd/utils/moderation/send_email.py
- BackEnd/validation/validate_profile.py
The logic for rejecting moderation request has been implemented.
Profile status is changed to 'blocked', profile is marked as deleted, user is marked as inactive. As a result, profile is no longer shown on the site, user cannot log in, and not allowed to sign up with the same email.
> #724 [BE] [Profile Moderation] Incorporate reject logic

- FrontEnd/src/components/authorization/LoginPage.jsx
- FrontEnd/src/components/moderation/ModerationModal.jsx
- FrontEnd/src/hooks/useProfile.js
The message 'Зміни успішно скасовано. Профіль компанії заблоковано' is displayed when moderator reject the moderation request. 
If the user is authorized at that moment the profile is blocked, he will be logged out.
When a user with a blocked profile tries to log in, he sees the toast message 'Профіль компанії було заблоковано внаслідок розміщення неприйнятного контенту' and is not allowed to log in.
> #733 [FE] [Moderation] Adjust UI according to 'Reject' logic

- BackEnd/profiles/models.py
- BackEnd/profiles/serializers.py
- BackEnd/profiles/templates/profiles/email_template.html
- BackEnd/profiles/tests/test_email_sending.py
- BackEnd/utils/moderation/handle_approved_images.py
- BackEnd/utils/moderation/image_moderation.py
- BackEnd/utils/moderation/send_email.py
- FrontEnd/src/utils/defineChanges.js
When images under moderation are deleted, an email should be sent indicating that the moderation request has been canceled. If only one image is deleted, the email should be sent with the remaining image still under moderation. **Additionally, when an image is deleted, it should be set to None in the profile.** Also, update the status to "undefined" when all content is deleted.
> #726 v2 handle moderation request for removed content

- BackEnd/profiles/tests/test_reject_moderation_request.py
Tests have been created for 'Reject' logic on a moderation request.
> #737 [BE] Create tests for 'Reject' logic on moderation request

- FrontEnd/src/components/adminPage/auto-approve-delay/AutoApproveDelay.jsx
- Adjust the error message to correspond to the project's style.
- Add error handling for the initial GET request.
- Change variable declaration to const.
> #762 [FE] Enhance AutoapproveDelay component  on Admin page

- FrontEnd/src/components/ProfilePage/FormComponents/DeleteProfileComponent/DeleteProfilePage.jsx
- FrontEnd/src/components/ProfilePage/ProfilePageComponents/ProfileContent.jsx
- FrontEnd/src/components/ProfilePage/UI/MyModal/MyModal.jsx
- FrontEnd/src/components/cookieacception/CookieMod.jsx
- FrontEnd/src/components/moderation/ModerationModal.jsx
Modal windows no longer close when clicking outside of them.
> #758 [FE] Prevent modal from closing when clicking outside of it

- .github/workflows/django_cd_dev.yml
- configs/nginx/nginx.conf
- docker-compose.dev.yml
- docker-compose.nginx.yml
Modified the Nginx configuration to directly serve Django media files, as Django does not serve them in production mode. The `location /media/ ` block was updated, and a volume mount for forum_media was added to the Nginx container. The unnecessary collectstatic command was also removed from django_cd_dev.
> Configure Nginx to serve Django media files

- FrontEnd/src/pages/AdminPage/Menu/Menu.jsx
There is duplication in the id's of admin menu items, that leads to a warning in the console.
> Fix duplication in the admin menu item IDs and adjust their order.

- BackEnd/administration/serializers.py
- BackEnd/administration/templates/administration/email_template.html
- BackEnd/administration/urls.py
- BackEnd/administration/views.py
- BackEnd/authentication/serializers.py
- BackEnd/requirements.txt
- BackEnd/utils/administration/create_password.py
- BackEnd/utils/administration/send_email.py
Back-end impelentation for admin registration.
> [Admin] [BackEnd] admin registration
