FrontEnd/main/src/components/landing-page/about-section/About.css
FrontEnd/main/src/components/landing-page/about-section/about-text/AboutText.css
FrontEnd/main/src/components/landing-page/about-section/cards/AboutCards.css
FrontEnd/main/src/components/landing-page/banner/Banner.css
FrontEnd/main/src/components/landing-page/companies/companies-product-cards/CompaniesProductCards.css
FrontEnd/main/src/components/landing-page/login-banner/LoginBanner.css
FrontEnd/main/src/components/landing-page/menu/Menu.css
FrontEnd/main/src/components/landing-page/partners/Partners.css

Fixed styles

---

docker-compose.yml

Created an alternative docker-compose file with the pgAdmin4 container
___
Closes #53

pgAdmin4 container added

---

code_conventions.md

Contains
frontend:
-  react + js naming rules
-  css naming rules
-  src structure  
Approved:

Draft of code conventions (frontend)

---

authentication/models.py

Passing password in create_superuser method fixed (password=None)

#105 Fix passing password in create_superuser method

---

authentication/authentication.py
authentication/tests/test_user_autologout.py
authentication/tests/test_user_login.py
authentication/tests/test_user_logout.py
authentication/tests/test_user_self.py
forum/settings.py

Functionality of auto logout after 2 weeks since the user login date was implemented.

#140  implement functionality of auto logout after 2 weeks

---

.gitignore
FrontEnd/.dockerignore
FrontEnd/Dockerfile
FrontEnd/docker-compose.yml
FrontEnd/nginx.conf
FrontEnd/package-lock.json
FrontEnd/package.json

Fixed docker file react

---

profiles/tests/test_activity.py
profiles/tests/test_category.py
profiles/urls.py
profiles/views.py

Implement endpoints, views for get requests from frontend for Category and Activity

#188 get category activity

---

profiles/permissions.py
profiles/serializers.py
profiles/tests/test_all_saved_companies.py
profiles/tests/test_crud_profile.py
profiles/tests/test_filter_profiles.py
profiles/tests/test_saved_companies_list.py
profiles/urls.py
profiles/views.py

All/saved companies functionality implemented. Field "saved" added to ProfileSerializer. It returns True, if company is in saved companies list of user. User's Companies saved list  returns by passing query param by "api/profiles/" endpoint. Due to this SavedCompanies functionality and test updated a little.

#172 All/saved companies functionality

---

forum/settings.py

IsAdmin permission was added to Djoser settings for user_list.

#197 User list permission added

---

profiles/filters.py
profiles/tests/test_filter_profiles.py

Redundant methods in filters removed, filters renamed according to model fields. Related tests updated.

#213 improve code in filters

---

profiles/tests/test_activity.py
profiles/tests/test_category.py
profiles/urls.py

Add slash to routes for activity and category, fix routes in tests

routeswith slash

---

FrontEnd/src/components/ProfilePage/FormComponents/GeneralInfo.js
FrontEnd/src/components/SignUp/components/signup/signup-form/SignUpFormContent.js

Change explicitly given base url (e.x. localhost:port) to the ones from the env file.
Changes required in:

229 change base urls in requests

---

docker-compose.yml
requirements.txt

add gunicorn to docker contaner

add gunicorn

---

administration/serializers.py
profiles/permissions.py
profiles/tests/test_saved_company.py
profiles/views.py

Fix bug with adding user's own company to SavedList
Fix bug to add company to another user's saved list

#192 saved company bug

---

.gitignore
forum/settings.py

* Added settings for static and media files
* Updated .gitignore

Public folders

---

FrontEnd/src/components/HeaderFooter/footer/top/FooterNavigation.jsx
FrontEnd/src/components/HeaderFooter/header/menu/HeaderMenu.jsx
FrontEnd/src/components/basicPage/BasicPage.jsx
FrontEnd/src/components/loader/Loader.jsx

clean up after merge conflict. some issues I missed after resolving merge conflict after linter was added.

Fix profile list bug

---

FrontEnd/.eslintrc.json
forum/settings.py
forum/urls.py
search/filters.py
search/serializers.py
search/tests.py
search/urls.py
search/views.py

Makar made a greate job and I don't want it to diy in that ancient PR. So I'll try to move it to develop. Just backend part

#add search functionality by makar

---

FrontEnd/src/components/basicPage/BasicPage.jsx
FrontEnd/src/components/landing-page/MainPage.jsx
FrontEnd/src/components/landing-page/banner/Banner.js
FrontEnd/src/components/landing-page/partners/Partners.css

Main page for authorized user was updated (blocks with "login" and "signup" buttons are not displayed). Redirect from signup page to profile page for authorized user was also added.

#272 update main page layout

---

forum/settings.py
forum/urls.py
requirements.txt
schema.yml

#280explore swagger

---

FrontEnd/src/components/ProfileDetail/MainInfo/TitleInfo.jsx

"Add to saved" button is hidden for profile owner

Add to saved button hidden for profile owner

---

FrontEnd/src/components/ProfileDetail/DetailedInfo/PhoneEmail.jsx
FrontEnd/src/components/ProfileDetail/DetailedInfo/PhoneEmail.module.css

View Contacts functionality updated according to backend and design changes:
- View contacts is available to unauthorized user too
- Fields "Показати телефон", "Показати ел. пошту" merged into field "Показати контакти"

#329 [FE] Update view contacts functionality

---

FrontEnd/src/components/ProfileDetail/DetailedInfo/ReadMore.module.css

Appropriate font styles applied to the text blocks instead of ant design styles.

#345 [Profile View] Fix styles in text blocks

---

FrontEnd/src/components/ProfilePage/FormComponents/FormFields/CheckBoxField.js
FrontEnd/src/components/ProfilePage/FormComponents/FormFields/CheckBoxField.module.css
FrontEnd/src/components/ProfilePage/FormComponents/FormFields/HalfFormField.module.css
FrontEnd/src/components/ProfilePage/FormComponents/GeneralInfo.js
FrontEnd/src/components/ProfilePage/ProfilePageComponents/ProfileContent.js
FrontEnd/src/components/ProfilePage/ProfilePageComponents/ProfileContent.module.css
FrontEnd/src/components/ProfilePage/UI/ProfileFormButton/ProfileFormButton.module.css

Profile editing updated:
- both Company and Startup options could be selected at the same time;
- appropriate tabs are active depending on selected option; 
- tooltips are added for disabled tabs;

#339 [Profile Edit] Ability to select company and startup

---

configs/nginx/nginx.conf
forum/settings.py
forum/urls.py
images/serializers.py
images/tests/test_banner.py
images/urls.py
images/views.py
profiles/models.py
profiles/serializers.py
profiles/urls.py
profiles/views.py

Uploading banner_image. User can add image to his company and get image of every company. Only BE part.

#174adding images

---

FrontEnd/src/components/SignUp/components/signup/signup-form/SignUpFormContent.js

User is redirected to modal sign-up window only in case of successful registration.

#352 Fix redirect to modal window after Sign Up

---

FrontEnd/src/components/ProfileDetail/MainInfo/TitleInfo.jsx
FrontEnd/src/components/ProfileDetail/MainInfo/TitleInfo.module.css

Redirect to Edit Profile page from Profile View page added for profile owner.

#331[Profile View] Redirect to edit profile

---

images/serializers.py
images/tests/test_logo.py
images/urls.py
images/views.py
profiles/tests/test_crud_profile.py

Adding images to logo_image field in Profile model. Just by previous schema. Only BE part

#356 add images to logo be

---

FrontEnd/src/components/ProfilePage/FormComponents/GeneralInfo.js

Company info max length increased as it was increased on backend side to 2000 characters.

#360 [Edit Profile] Company info max length increased

---

FrontEnd/src/components/ProfileDetail/DetailedInfo/CompanyDescription.jsx
FrontEnd/src/components/ProfileDetail/MainInfo/ProfileDetailNavBar.jsx

The logic of shown tabs and fields updated so that only related to the type of company tabs and fields are shown.
Previously filled fields were shown in any case.

#340-Tabs shown depending on Company/Startup choice

---

FrontEnd/src/components/ProfileDetail/MainInfo/TitleInfo.module.css
FrontEnd/src/components/ProfilePage/ProfilePageComponents/Description.module.css
FrontEnd/src/components/SearchPage/search_field/companies/CompanyCard.jsx
FrontEnd/src/components/SearchPage/search_field/companies/CompanyCard.module.css
FrontEnd/src/components/profileList/ProfileCard.module.css

Appropriate styles for logo image added on Edit Profile page.
"object-fit: cover" property added to logo image styles to resize it in a proper way.
Default logo image added to company card in search.

#372 Fix logo image styles

---

FrontEnd/package-lock.json
FrontEnd/package.json
FrontEnd/src/components/ProfilePage/FormComponents/GeneralInfo.js
FrontEnd/src/components/RestorePassword/components/restorepassword/restorepassword-form/EmailFormContent.js
FrontEnd/src/components/SignUp/components/signup/signup-form/ResendActivationFormContent.js
FrontEnd/src/components/basicPage/BasicPage.jsx
FrontEnd/src/components/basicPage/BasicPage.module.css
FrontEnd/src/index.css

The user is notified if company with such edrpou already exists, when attempting to save data in General Info tab.
UPD.: 
ToastContainer removed from components and added to BasicPage. Also custom styles added to it, it's displayed now as per design.  (Design provides styles for error notifications on Login page.) So all the notifications are styled the same way now.

#362 [Edit Profile] Notification edrpou already exists

---

README.md
forum/settings.py

Wiki add:
https://github.com/ita-social-projects/Forum/wiki/License:
https://github.com/ita-social-projects/Forum/wiki/Tech-documentation
https://github.com/ita-social-projects/Forum/wiki/Project-Launch-Instructions
Format readmy.txt

#281 implement documentation for the project

---

FrontEnd/src/components/ProfileDetail/MainInfo/TitleInfo.jsx
FrontEnd/src/components/ProfileDetail/MainInfo/TitleInfo.module.css
FrontEnd/src/components/profileList/ProfileCard.jsx
FrontEnd/src/components/profileList/ProfileCard.module.css
FrontEnd/src/tests/CompanyCard.test.js

Functionality has been updated - all the categories are displayed on the profile page and on the list of companies.

#335 View profile/list: display many categories

---

FrontEnd/src/components/ProfilePage/ProfilePageComponents/Description.js

Subheaders text on the Edit Profile page has been adjusted according to the requirements:
1. "Інформація про користувача платформи" for "Інформація про користувача" section
2. "Інформація про компанію" for "Загальна інформація", "Контакти", "Інформація про товари/послуги", "Додаткова інформація",
3. "Інформація про стартап" for "Стартап" section

#380 [Edit Profile] Subheaders text about kind of changes

---

FrontEnd/src/components/ProfilePage/FormComponents/GeneralInfo.js

setProfile was added to uploadImage to update current values of banner and logo fields after changes saved.

#419 [Edit Profile] Fix notification about unsaved changes

---

FrontEnd/src/components/ProfileDetail/DetailedInfo/DataContacts.jsx
FrontEnd/src/components/ProfileDetail/ProfileDetailPage.jsx
FrontEnd/src/components/ProfilePage/FormComponents/WarnUnsavedDataModal.jsx

UI bug fixed - missing letter was added.
Extra bugs fixed:
- condition for displaying text "Інформація не заповнена"  was corrected;
- prop type was corrected.

#438 [Profile] Fix UI defects

---

authentication/serializers.py
authentication/tests/test_user_login.py
authentication/tests/test_user_logout.py
forum/settings.py
images/tests/test_banner.py
images/tests/test_logo.py
profiles/managers.py
profiles/tests/test_new_members.py
requirements.txt

I used library: https://github.com/tomasbasham/ratelimit
For now if user login 10 times in 10 minuts (no matter with wrong or right credentials) this url will be blocked for this user untill 10 minuts will finish.

#378 add the limitation of login

---

FrontEnd/src/components/SignUp/components/signup/signup-form/SignUpFormContent.js
FrontEnd/src/components/SignUp/components/signup/signup-form/SignUpFormContent.module.css
FrontEnd/src/components/authorization/LoginPage.jsx
FrontEnd/src/constants/constants.js

fixed errors that were in task #437

#437 fix UI defects registration page

---

.github/workflows/django_ci.yml
.github/workflows/tests_be.yml
README.md
forum/settings.py
forum/test_setting.py

Divide settings for dev and tests(to escape if-statement in settings.py file)
New command for running tests:
docker compose -f docker-compose.dev.yml exec api-dev python manage.py test --settings=forum.test_setting

test setting

---

FrontEnd/src/components/ProfileDetail/DetailedInfo/DataContacts.jsx
FrontEnd/src/components/ProfileDetail/ProfileDetailPage.jsx
FrontEnd/src/components/ProfilePage/FormComponents/FormComponents.module.css
FrontEnd/src/components/ProfilePage/FormComponents/FormFields/CheckBoxField.js
FrontEnd/src/components/ProfilePage/FormComponents/GeneralInfo.js
FrontEnd/src/utils/checkFormIsDirty.js

The functionality of filling out the IPN field has been implemented. 
'ФОП' field ensures proper handling. Users are notified about related to the IPN field errors, when try to save changes. 
I have some doubts about the error texts. I would appreciate any suggestions for improvement.

#465 Implement the functionality of filling out IPN

---

FrontEnd/src/components/ProfileDetail/MainInfo/TitleInfo.jsx
FrontEnd/src/components/ProfileDetail/MainInfo/TitleInfo.module.css
profiles/serializers.py
search/serializers.py
utils/regions_ukr_names.py

For long regions: 
And for short:

serializer, TitleInfo

---

FrontEnd/src/components/CompanyCard/CompanyCard.jsx
FrontEnd/src/components/CompanyCard/CompanyCard.module.css
FrontEnd/src/components/MiniComponents/CategoryBadges.jsx
FrontEnd/src/components/MiniComponents/StarForLike.jsx
FrontEnd/src/components/MiniComponents/StarForLike.module.css
FrontEnd/src/components/ProfileDetail/MainInfo/TitleInfo.jsx
FrontEnd/src/components/profileList/ProfileCard.jsx

Make star for like and category badges reusable

StarForLike, CategoryBadges

---

docker-compose.dev.yml
forum/settings.py

Our site can't get images for banner and logo after redeploy. I think I fixed it. I tried it on redeploy 3 times and it worked.

#saving pictures problem

---

FrontEnd/src/components/ProfileDetail/DetailedInfo/PhoneEmail.jsx
FrontEnd/src/components/ProfileDetail/DetailedInfo/PhoneEmail.module.css

Added icons that, when clicked on, copy phone or email to clipboard. 
Icons provided by Ant Design
When clicked, icon change to green 'clicked' one.
After 4 sec the icon change back to 'copy' one. 
Class .contact-container added to classes.
Path to file with changes: FrontEnd/src/components/ProfileDetail/DetailedInfo/PhoneEmail.jsx

#477 add the possibility to copy fields content

---

FrontEnd/src/components/profileList/ProfileListPage.jsx

fixed a bug in the other services tab filter

fixed a bug in the other services tab

---

FrontEnd/src/components/SignUp/components/signup/signup-form/SignUpFormContent.js

The bug with the business entity checkboxes has been fixed. Now, both a company and an entrepreneur can be registered.

#535 [Registration] Fix bug with business entity checkboxes

---

profiles/tests/test_filter_profiles.py

After correcting the operation of the "other services" tab, I added tests for this type of company activity

added tests to the company's type of activity, other services

---

FrontEnd/src/components/ProfilePage/FormComponents/ChangePassword.js
FrontEnd/src/components/ProfilePage/FormComponents/FormFields/PasswordField.js
FrontEnd/src/components/ProfilePage/FormComponents/FormFields/PasswordField.module.css

Changed the required field message to align with the project's style

---

profiles/fixtures/categories.yaml

Add categories according to https://github.com/ita-social-projects/Forum/issues/366

add categories

---

FrontEnd/src/components/ProfilePage/FormComponents/FormFields/PasswordField.module.css

Added css for label in PasswordField

---

FrontEnd/src/components/ProfilePage/FormComponents/AdditionalInfo.js
FrontEnd/src/components/ProfilePage/FormComponents/ContactsInfo.js
FrontEnd/src/components/ProfilePage/FormComponents/DeleteProfileComponent/DeleteProfileModal.js
FrontEnd/src/components/ProfilePage/FormComponents/FormComponents.module.css
FrontEnd/src/components/ProfilePage/FormComponents/FormFields/CheckBoxField.js
FrontEnd/src/components/ProfilePage/FormComponents/FormFields/FullField.js
FrontEnd/src/components/ProfilePage/FormComponents/FormFields/FullField.module.css
FrontEnd/src/components/ProfilePage/FormComponents/FormFields/HalfFormField.js
FrontEnd/src/components/ProfilePage/FormComponents/FormFields/HalfFormField.module.css
FrontEnd/src/components/ProfilePage/FormComponents/FormFields/ImageField.js
FrontEnd/src/components/ProfilePage/FormComponents/FormFields/MultipleSelectChip.js
FrontEnd/src/components/ProfilePage/FormComponents/FormFields/PasswordField.js
FrontEnd/src/components/ProfilePage/FormComponents/FormFields/TextField.js
FrontEnd/src/components/ProfilePage/FormComponents/GeneralInfo.js
FrontEnd/src/components/ProfilePage/FormComponents/UserInfo.js
FrontEnd/src/components/SignUp/components/signup/signup-form/SignUpFormContent.js
FrontEnd/src/components/SignUp/components/signup/signup-form/SignUpFormContent.module.css
FrontEnd/src/constants/constants.js
FrontEnd/src/utils/preventEnterSubmit.js

Field validation has been updated according to the requirements. 
Notification, that changes cannot be saved due to errors in the form, has been added. 
Submitting changes by pressing Enter in input fields has been disabled on the edit profile page.

#534 Improve fields validation on the Registration form and Edit profile page

---

FrontEnd/src/components/basicPage/BasicPage.jsx

Added redirection to the 404 page for non-existent urls

---

BackEnd/forum/apps.py
BackEnd/forum/schema.py
BackEnd/forum/settings.py
BackEnd/profiles/serializers.py
BackEnd/profiles/views.py
BackEnd/search/serializers.py

Errors and warnings that appeared during schema generation for the API documentation have been fixed.

#582 Fix Swagger schema generation errors

---

FrontEnd/src/components/ProfilePage/FormComponents/UserInfo.jsx

Validation has been fixed on the "Інформація про користувача" page:
- User is not allowed to enter more than 50 symbols (person position field).
- User is not allowed to save incorrect data.

#628 User info fields validation fixed

---

FrontEnd/src/components/Contact/Contact.jsx
FrontEnd/src/components/CookiesPolicyPage/CookiesPolicyComponent.jsx
FrontEnd/src/components/HeaderFooter/footer/top/FooterNavigation.jsx
FrontEnd/src/components/PrivacyPolicyPage/PrivacyPolicyPage.jsx
FrontEnd/src/components/terms-and-conditions-app/terms_conditions/TermsAndConditionsComponent.jsx
FrontEnd/src/hooks/useScrollToTop.js

Preconditions
The http://178.212.110.52/ is opened
The "Головна" page is opened
Steps to reproduce
Scroll down to the end of the page
Click on the "Компанії" tab
Actual result
The User is redirected to the end of the "Компанії" page

add useScrollToTop.js to hooks

---

FrontEnd/src/components/CookiesPolicyPage/LinkContainer.jsx
FrontEnd/src/components/HeaderFooter/footer/top/FooterPolicy.jsx
FrontEnd/src/components/HeaderFooter/footer/top/FooterPolicy.module.css
FrontEnd/src/components/PrivacyPolicyPage/PrivacyPolicy.module.css
FrontEnd/src/components/PrivacyPolicyPage/text.js

updated privacy policy

---

FrontEnd/src/components/ProfilePage/FormComponents/AdditionalInfo.jsx
FrontEnd/src/components/ProfilePage/FormComponents/ContactsInfo.jsx
FrontEnd/src/components/ProfilePage/FormComponents/GeneralInfo.jsx
FrontEnd/src/components/ProfilePage/FormComponents/ProductServiceInfo.jsx
FrontEnd/src/components/ProfilePage/FormComponents/StartupInfo.jsx
FrontEnd/src/components/ProfilePage/FormComponents/UserInfo.jsx
FrontEnd/src/components/ProfilePage/ProfilePageComponents/ProfileContent.jsx
FrontEnd/src/components/ProfilePage/UI/ProfileFormButton/ProfileFormButton.jsx
FrontEnd/src/utils/defineChanges.js

The form is submitted only if any field is changed. Only changed fields are included in the patch request.

#690 [Edit Profile] Update form submission

---

FrontEnd/src/components/ProfilePage/FormComponents/AdditionalInfo.jsx
FrontEnd/src/components/ProfilePage/FormComponents/ContactsInfo.jsx
FrontEnd/src/components/ProfilePage/FormComponents/FormFields/CheckBoxField.jsx
FrontEnd/src/components/ProfilePage/FormComponents/FormFields/FullField.jsx
FrontEnd/src/components/ProfilePage/FormComponents/FormFields/HalfFormField.jsx
FrontEnd/src/components/ProfilePage/FormComponents/FormFields/MultipleSelectChip.jsx
FrontEnd/src/components/ProfilePage/FormComponents/FormFields/TextField.jsx
FrontEnd/src/components/ProfilePage/FormComponents/GeneralInfo.jsx
FrontEnd/src/components/ProfilePage/FormComponents/ProductServiceInfo.jsx
FrontEnd/src/components/ProfilePage/FormComponents/StartupInfo.jsx
FrontEnd/src/components/ProfilePage/FormComponents/UserInfo.jsx

A typo has been fixed in Profile Page components (requred -> required).

#701 [Edit Profile] Fix typo in Profile Page components (requred -> required)

---

FrontEnd/src/utils/defineChanges.js

An error in the defineChanges function that occurred when the image was deleted and the Submit button was clicked has been fixed.

#708 [Edit Profile] Fix image deletion bug

---

BackEnd/profiles/tests/test_email_sending.py

Created unit tests to verify email sending and check the email content. Also, implemented unit tests to validate the methods of the manager class.

#713 tests for email sending functionality

---

BackEnd/profiles/serializers.py
BackEnd/profiles/tests/test_approve_moderation_request.py

Tests have been created for 'Approve' logic on a moderation request.

#727 [BE] Create tests for 'Approve' logic on moderation request

---

FrontEnd/src/components/ProfileDetail/DetailedInfo/DataContacts.jsx
FrontEnd/src/components/ProfileDetail/DetailedInfo/PhoneEmail.jsx
FrontEnd/src/components/ProfileDetail/ProfileDetailPage.jsx
FrontEnd/src/components/profileList/ProfileListPage.jsx
FrontEnd/src/context/AuthContextProvider.js

The functionality to notify user (toast message) about expired session if he is automatically logged out due to an expired token has been added.

#745 [FE] Notify logged out user about expired session

---

FrontEnd/src/components/basicPage/customTheme.js
FrontEnd/src/components/basicPage/customToastStyles.css
FrontEnd/src/global.css

fix Bug css

---

FrontEnd/package-lock.json
FrontEnd/package.json
FrontEnd/src/components/SignUp/components/signup/signup-form/SignUpFormContent.jsx
FrontEnd/src/components/SignUp/components/signup/signup-form/SignUpFormContent.module.css
FrontEnd/src/components/authorization/LoginPage.module.css

An error is shown now when the password doesn't meet the requirements, even if the Password and Confirm password fields are equal.

#776 [Registration] Fix password field validation

---

FrontEnd/src/components/SignUp/pages/SignUpModalPage.jsx

fixed console error

---

FrontEnd/src/components/landing-page/about-section/About.css
FrontEnd/src/components/landing-page/about-section/About.jsx

When you go to "Про нас" you are redirected to the page without scrolling down to the needed section

reditect about-us

---

BackEnd/profiles/fixtures/activities.yaml

BackEnd/profiles/fixtures/activities.yaml has been updated.

[BE] CorrectSyntaxErrorInFixture

---

BackEnd/administration/factories.py
BackEnd/administration/filters.py
BackEnd/administration/serializers.py
BackEnd/administration/tests/test_admin_user.py
BackEnd/administration/views.py

Admin panel users list
json format 
```  {
"id": 47,
"email": "is_deleted_******_***@test.ua",
"name": "test",
"surname": "test",
"status": {
"is_active": false,
"is_staff": false,
"is_superuser": false,
"is_deleted": true
},
"company_name": "test",
"registration_date": "2024-10-18"
}
```
Filter (sort, direction and status)
```
Filters
/?id= , /?surname=, /?email= , /?is_active= , /?is_staff=,
/?is_superuser=,  /?is_deleted=True or False,  /?company_name=, /?registration_date=,
Ordering sample
/?ordering=id asc or /?ordering=-id desc
```

#822 view users list
